name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 34
          target: google_apis/x86_64
          arch: x86_64
          emulator: true

      - name: Install system image
        run: sdkmanager "system-images;android-30;google_apis;x86_64"

      - name: Create AVD
        run: echo "no" | avdmanager create avd -n test -k "system-images;android-30;google_apis;x86_64" --device "pixel"

      - name: Start emulator
        run: |
          adb devices
          echo "Starting emulator..."
          nohup emulator -avd test -no-window -no-audio -no-snapshot -no-boot-anim &
          adb wait-for-device
          adb shell input keyevent 82

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build the project
        run: ./gradlew build

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest

      - name: Run instrumented tests
        run: ./gradlew connectedDebugAndroidTest
