name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 30
          target: google_apis/arm64-v8a
          arch: arm64-v8a
          emulator: true

      - name: Install ARM system image
        run: sdkmanager "system-images;android-30;google_apis;arm64-v8a"

      - name: Install emulator
        run: sdkmanager "emulator"

      - name: Add emulator to PATH
        run: echo "${ANDROID_SDK_ROOT}/emulator" >> $GITHUB_PATH

      - name: Verify emulator installation
        run: which emulator

      - name: Create AVD with ARM
        run: echo "no" | avdmanager create avd -n test -k "system-images;android-30;google_apis;arm64-v8a" --device "pixel"

      - name: Start emulator with ARM
        run: |
          echo "Starting ARM emulator..."
          nohup ${ANDROID_SDK_ROOT}/emulator/emulator -avd test -no-window -no-audio -no-snapshot -no-boot-anim -gpu swiftshader_indirect &
          echo "Waiting for emulator to boot..."
          adb wait-for-device
          adb shell input keyevent 82

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build the project
        run: ./gradlew build

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest

      - name: Run instrumented tests
        run: ./gradlew connectedDebugAndroidTest
